#!/bin/bash

#this script is used to run the paperless-ng container on a laptop
#rather than letting the container and docker daemon run continously, i'd like to have it off by default
#this script will check if it's running, then turn it on, and turn it off when browser window is closed

#Set variables to reduce clutter
CONTAINER="docker-compose -f /path/to/docker-compose.yml up -d"
STATUS="docker-compose -f /path/to/docker-compose.yml ps -a"

#if the containres aren't running, turn them on, wait before 
if [ $( docker ps -a -f name=paperless* | wc -l ) -eq 5 ]; then
  echo "paperless-ng is running"
else
   echo "paerless-ng is NOT running, turning on containers now, please wait"
   $CONTAINER
   sleep 30
   $STATUS  
fi
#start web browser and navigate to paperless-ng webui
xdg-open http://127.0.0.1:8000

#open simple-scan 
simple-scan </dev/null> &>/dev/null & 

#wait until the user confirms  they are done
read -p "Press any key when scanning is finished"

#kill simple-scanner
sudo pkill simple-scan

#turn off containers
docker-compose -f /path/to/docker-compose.yml ocker-compose.yml down

#shut down the browser session
wmctrl -c "Paperless-ng"

